# Generated by Django 4.2 on 2025-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieentry',
            name='food',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
