# Generated by Django 4.2 on 2025-04-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_weight_calorieentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CalorieEntry',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
